#!/bin/bash
set -e

npm run build

ssh schemed -t "
  sudo rm -rf /var/www/schemed-web/*
  sudo chown -R www-data:www-data /var/www/schemed-web
"

rsync -avz --progress \
  -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
  ./build/* \
  schemed:/var/www/schemed-web/
